import { Metadata } from 'next'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Shield, Lock, Heart, Eye, Database, UserCheck } from 'lucide-react'

export const metadata: Metadata = {
    title: 'Privacy & Child Safety - Safe AI Stories',
    description:
        'Learn how Safe AI Stories protects your child\'s privacy and ensures 100% kid-safe content. COPPA compliant, no data selling, advanced safety filters.',
    keywords: [
        'child privacy',
        'kid-safe ai',
        'coppa compliant',
        'child safety online',
        'ai content safety',
    ],
}

export default function PrivacyPage() {
    return (
        <main className="min-h-screen bg-gradient-hero">
            {/* Header */}
            <section className="bg-gradient-to-r from-green-500 via-emerald-500 to-teal-500 py-20 px-4">
                <div className="container mx-auto max-w-4xl text-center">
                    <div className="flex justify-center mb-6">
                        <div className="h-20 w-20 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center">
                            <Shield className="h-10 w-10 text-white" />
                        </div>
                    </div>
                    <h1 className="text-5xl md:text-6xl font-bold text-white mb-6 drop-shadow-lg">
                        Privacy & Child Safety
                    </h1>
                    <p className="text-xl md:text-2xl text-white/90 max-w-3xl mx-auto font-semibold">
                        Your child's safety and privacy are our top priorities. Here's how we protect them.
                    </p>
                </div>
            </section>

            {/* Main Content */}
            <section className="py-16 px-4">
                <div className="container mx-auto max-w-4xl">
                    {/* Child Safety */}
                    <Card className="mb-8 border-4 border-border bg-white shadow-xl">
                        <CardHeader className="bg-gradient-to-br from-primary/20 to-accent/20 border-b-4 border-border">
                            <div className="flex items-center gap-3">
                                <Shield className="h-8 w-8 text-green-600" />
                                <CardTitle className="text-3xl font-bold text-gray-800">
                                    100% Kid-Safe Content
                                </CardTitle>
                            </div>
                        </CardHeader>
                        <CardContent className="pt-6 space-y-4">
                            <p className="text-gray-700 text-lg leading-relaxed">
                                Every story generated by Safe AI Stories passes through multiple layers of safety filters
                                to ensure age-appropriate, wholesome content.
                            </p>

                            <h3 className="text-xl font-bold text-gray-800 mt-6">Our Safety Process:</h3>
                            <ul className="space-y-3">
                                {[
                                    'AI Content Filtering: Advanced algorithms screen for inappropriate themes, language, or concepts',
                                    'Age-Appropriate Validation: Stories are tailored to your child\'s developmental stage',
                                    'Human Oversight: Random story audits ensure quality and safety standards',
                                    'Continuous Improvement: We update our filters based on parent feedback and child development research',
                                    'No Scary Content: We avoid violence, fear-inducing themes, or nightmares triggers',
                                ].map((item, idx) => (
                                    <li key={idx} className="flex items-start gap-3">
                                        <div className="h-6 w-6 rounded-full bg-green-500 flex items-center justify-center flex-shrink-0 mt-0.5">
                                            <span className="text-white text-sm font-bold">{idx + 1}</span>
                                        </div>
                                        <span className="text-gray-700">{item}</span>
                                    </li>
                                ))}
                            </ul>
                        </CardContent>
                    </Card>

                    {/* Privacy Protection */}
                    <Card className="mb-8 border-4 border-primary/30 bg-white shadow-xl">
                        <CardHeader className="bg-gradient-primary border-b-4 border-primary/30">
                            <div className="flex items-center gap-3">
                                <Lock className="h-8 w-8 text-blue-600" />
                                <CardTitle className="text-3xl font-bold text-gray-800">
                                    Privacy Protection
                                </CardTitle>
                            </div>
                        </CardHeader>
                        <CardContent className="pt-6 space-y-4">
                            <p className="text-gray-700 text-lg leading-relaxed">
                                We take your family's privacy seriously. Here's our commitment to you:
                            </p>

                            <div className="grid md:grid-cols-2 gap-6 mt-6">
                                {[
                                    {
                                        icon: Database,
                                        title: 'No Data Selling',
                                        desc: 'We will NEVER sell your data or your child\'s information to third parties. Ever.',
                                    },
                                    {
                                        icon: Lock,
                                        title: 'Secure Storage',
                                        desc: 'All data is encrypted in transit and at rest using industry-standard encryption.',
                                    },
                                    {
                                        icon: Eye,
                                        title: 'Minimal Collection',
                                        desc: 'We only collect what\'s necessary to provide the service—nothing more.',
                                    },
                                    {
                                        icon: UserCheck,
                                        title: 'Parent Control',
                                        desc: 'You can view, export, or delete all your data anytime from your account.',
                                    },
                                ].map((item, idx) => (
                                    <div key={idx} className="flex items-start gap-3 p-4 bg-muted rounded-lg">
                                        <item.icon className="h-6 w-6 text-blue-600 flex-shrink-0 mt-1" />
                                        <div>
                                            <h4 className="font-bold text-gray-800 mb-1">{item.title}</h4>
                                            <p className="text-gray-600 text-sm">{item.desc}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </CardContent>
                    </Card>

                    {/* COPPA Compliance */}
                    <Card className="mb-8 border-4 border-primary/30 bg-white shadow-xl">
                        <CardHeader className="bg-gradient-primary border-b-4 border-primary/30">
                            <div className="flex items-center gap-3">
                                <Heart className="h-8 w-8 text-purple-600" />
                                <CardTitle className="text-3xl font-bold text-gray-800">
                                    COPPA Compliance
                                </CardTitle>
                            </div>
                        </CardHeader>
                        <CardContent className="pt-6 space-y-4">
                            <p className="text-gray-700 text-lg leading-relaxed">
                                Safe AI Stories complies with the Children's Online Privacy Protection Act (COPPA), which
                                protects the privacy of children under 13.
                            </p>

                            <h3 className="text-xl font-bold text-gray-800 mt-6">What This Means:</h3>
                            <ul className="space-y-3">
                                {[
                                    'We obtain verifiable parental consent before collecting any personal information from children',
                                    'Parents can review, delete, or refuse further collection of their child\'s information',
                                    'We don\'t condition a child\'s participation on providing more information than necessary',
                                    'We maintain reasonable security procedures to protect collected information',
                                ].map((item, idx) => (
                                    <li key={idx} className="flex items-start gap-3">
                                        <Heart className="h-5 w-5 text-purple-600 flex-shrink-0 mt-1" />
                                        <span className="text-gray-700">{item}</span>
                                    </li>
                                ))}
                            </ul>
                        </CardContent>
                    </Card>

                    {/* What We Collect */}
                    <Card className="mb-8 border-4 border-accent bg-white shadow-xl">
                        <CardHeader className="bg-gradient-secondary border-b-4 border-accent">
                            <CardTitle className="text-3xl font-bold text-gray-800">
                                What Information We Collect
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="pt-6 space-y-4">
                            <div className="space-y-6">
                                <div>
                                    <h3 className="text-xl font-bold text-gray-800 mb-2">Parent Account Information:</h3>
                                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                                        <li>Email address (for account access and communication)</li>
                                        <li>Payment information (processed securely through Stripe)</li>
                                        <li>Account preferences and settings</li>
                                    </ul>
                                </div>

                                <div>
                                    <h3 className="text-xl font-bold text-gray-800 mb-2">Child Profile Information:</h3>
                                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                                        <li>First name (used in stories)</li>
                                        <li>Age (to ensure age-appropriate content)</li>
                                        <li>Interests (optional, for story personalization)</li>
                                    </ul>
                                    <p className="text-sm text-gray-600 mt-2 italic">
                                        Note: We never collect last names, addresses, phone numbers, or photos of children.
                                    </p>
                                </div>

                                <div>
                                    <h3 className="text-xl font-bold text-gray-800 mb-2">Usage Information:</h3>
                                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                                        <li>Stories created (to save your library)</li>
                                        <li>Feature usage (to improve the service)</li>
                                        <li>Technical data (device type, browser, for compatibility)</li>
                                    </ul>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Your Rights */}
                    <Card className="border-4 border-primary/30 bg-white shadow-xl">
                        <CardHeader className="bg-gradient-primary border-b-4 border-primary/30">
                            <CardTitle className="text-3xl font-bold text-gray-800">Your Rights</CardTitle>
                        </CardHeader>
                        <CardContent className="pt-6 space-y-4">
                            <p className="text-gray-700 text-lg leading-relaxed">
                                You have complete control over your family's data:
                            </p>

                            <ul className="space-y-3">
                                {[
                                    'Access: View all data we have about you and your child',
                                    'Export: Download your data in a portable format',
                                    'Delete: Permanently delete your account and all associated data',
                                    'Correct: Update or correct any inaccurate information',
                                    'Opt-Out: Unsubscribe from marketing emails anytime',
                                ].map((item, idx) => (
                                    <li key={idx} className="flex items-start gap-3">
                                        <div className="h-6 w-6 rounded-full bg-primary flex items-center justify-center flex-shrink-0 mt-0.5">
                                            <span className="text-white text-sm font-bold">✓</span>
                                        </div>
                                        <span className="text-gray-700">{item}</span>
                                    </li>
                                ))}
                            </ul>

                            <p className="text-gray-700 mt-6">
                                To exercise any of these rights, contact us at{' '}
                                <a href="mailto:privacy@safeaistories.com" className="text-pink-600 font-semibold hover:underline">
                                    privacy@safeaistories.com
                                </a>
                            </p>
                        </CardContent>
                    </Card>

                    {/* Contact */}
                    <div className="mt-12 text-center">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">Questions About Privacy or Safety?</h2>
                        <p className="text-gray-700 mb-6">
                            We're here to help. Reach out anytime with concerns or questions.
                        </p>
                        <a
                            href="mailto:support@safeaistories.com"
                            className="inline-block bg-gradient-to-r from-green-500 to-emerald-500 text-white font-bold px-8 py-4 rounded-full shadow-lg hover:shadow-xl transform hover:scale-105 transition-all"
                        >
                            Contact Support
                        </a>
                    </div>
                </div>
            </section>
        </main>
    )
}
