import { Metadata } from 'next'
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Shield, Lock, Heart, Eye, Database, UserCheck } from 'lucide-react'
import { ArticleSchema } from '@/components/schema/schema-markup'

export const metadata: Metadata = {
    title: 'Privacy & Child Safety Policy | AI Tales',
    description:
        'Learn how AI Tales protects your child\'s privacy and ensures 100% kid-safe content. COPPA compliant, no data selling, advanced safety filters. Human-moderated AI stories.',
    keywords: [
        'AI Tales privacy policy',
        'child privacy protection',
        'kid-safe AI content',
        'COPPA compliant stories',
        'child safety online',
        'AI content safety',
        'children\'s data privacy',
        'safe AI stories privacy',
    ],
    openGraph: {
        title: 'Privacy & Child Safety Policy | AI Tales',
        description: 'Learn how AI Tales protects your child\'s privacy and ensures 100% kid-safe content. COPPA compliant, no data selling, advanced safety filters.',
        url: 'https://ai-tales.com/privacy',
        images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'AI Tales Privacy Policy' }],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Privacy & Child Safety Policy | AI Tales',
        description: 'Learn how AI Tales protects your child\'s privacy and ensures 100% kid-safe content. COPPA compliant, no data selling.',
    },
}

export default function PrivacyPage() {
  return (
    <>
      <ArticleSchema
        title="Privacy & Child Safety Policy - AI Tales"
        description="Learn how AI Tales protects your child's privacy and ensures 100% kid-safe content. COPPA compliant, no data selling, advanced safety filters."
        datePublished="2024-01-01"
        dateModified="2024-12-01"
        authorName="AI Tales Team"
        imageUrl="https://ai-tales.com/og-image.png"
      />
      <main className="min-h-screen playwize-bg relative selection:bg-playwize-purple selection:text-white py-20 px-4 overflow-hidden">
      {/* Background Ornaments */}
      <div className="absolute top-40 -left-20 w-80 h-80 circle-pattern opacity-30 pointer-events-none" />
      <div className="absolute top-[60%] -right-20 w-96 h-96 circle-pattern opacity-30 pointer-events-none" />

      <div className="max-w-4xl mx-auto space-y-16 relative z-10">
        {/* Header */}
        <div className="text-center space-y-6">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-green-100 text-green-600 text-sm font-bold border border-green-200">
            <Shield className="h-4 w-4" />
            <span>Safety First</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black text-gray-900 tracking-tight leading-[1.1]">
            Privacy & <br />
            <span className="text-playwize-purple">Child Safety</span>
          </h1>
          <p className="text-xl text-gray-600 font-medium leading-relaxed max-w-2xl mx-auto">
            Your child's safety and privacy are our top priorities. Here's our unbreakable commitment to protecting your family.
          </p>
        </div>

        {/* Main Content */}
        <div className="grid gap-8">
          {/* Child Safety Card */}
          <div className="bg-white p-10 md:p-12 rounded-[3.5rem] border-4 border-gray-100 shadow-sm space-y-8 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-green-50 rounded-full -mr-10 -mt-10" />
            <div className="flex items-center gap-4 relative z-10">
              <div className="h-14 w-14 rounded-2xl bg-green-100 flex items-center justify-center">
                <Shield className="h-8 w-8 text-green-600" />
              </div>
              <h2 className="text-3xl font-black text-gray-900">100% Kid-Safe Content</h2>
            </div>
            
            <div className="space-y-6 relative z-10">
              <p className="text-lg text-gray-600 font-bold leading-relaxed italic border-l-4 border-green-200 pl-6">
                Every story generated by AI Tales passes through multiple layers of safety filters to ensure age-appropriate, wholesome content. Our human-moderated AI ensures 100% kid-safe stories for children ages 3-12.
              </p>

              <div className="grid gap-4 mt-8">
                {[
                  'AI Content Filtering: Advanced algorithms screen for inappropriate themes.',
                  'Age-Appropriate Validation: Stories tailored to developmental stages.',
                  'Human Oversight: Random story audits for quality standards.',
                  'Continuous Improvement: Updated based on parent feedback.',
                  'No Scary Content: Zero violence or fear-inducing themes.',
                ].map((item, idx) => (
                  <div key={idx} className="flex items-center gap-4 p-4 bg-gray-50 rounded-2xl border-2 border-white shadow-sm">
                    <div className="h-8 w-8 rounded-full bg-green-500 text-white font-black flex items-center justify-center shrink-0">
                      {idx + 1}
                    </div>
                    <span className="text-gray-700 font-bold">{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Privacy Protection Card */}
          <div className="bg-white p-10 md:p-12 rounded-[3.5rem] border-4 border-gray-100 shadow-sm space-y-10 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-full -mr-10 -mt-10" />
            <div className="flex items-center gap-4 relative z-10">
              <div className="h-14 w-14 rounded-2xl bg-blue-100 flex items-center justify-center">
                <Lock className="h-8 w-8 text-blue-600" />
              </div>
              <h2 className="text-3xl font-black text-gray-900">Privacy Protection</h2>
            </div>

            <div className="grid md:grid-cols-2 gap-6 relative z-10">
              {[
                { icon: Database, title: 'No Data Selling', desc: 'We will NEVER sell your data to third parties.' },
                { icon: Lock, title: 'Secure Storage', desc: 'Industry-standard encryption for all data.' },
                { icon: Eye, title: 'Minimal Collection', desc: 'We only collect what is absolutely necessary.' },
                { icon: UserCheck, title: 'Parent Control', desc: 'Export or delete your data at any time.' },
              ].map((item, idx) => (
                <div key={idx} className="p-6 bg-blue-50/50 rounded-[2.5rem] border-2 border-white shadow-sm space-y-3">
                  <div className="h-12 w-12 rounded-2xl bg-white flex items-center justify-center shadow-sm">
                    <item.icon className="h-6 w-6 text-blue-600" />
                  </div>
                  <h4 className="font-black text-gray-900">{item.title}</h4>
                  <p className="text-gray-500 font-bold text-sm leading-relaxed">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Rights & Contact */}
          <div className="text-center space-y-8 pt-8">
            <h3 className="text-2xl font-black text-gray-900">Questions About Privacy?</h3>
            <p className="text-gray-500 font-bold max-w-xl mx-auto">
              We are here to help. Reach out anytime with concerns or questions at{' '}
              <a href="mailto:privacy@safeaistories.com" className="text-playwize-purple underline">privacy@safeaistories.com</a>
            </p>
            <a
              href="mailto:support@safeaistories.com"
              className="inline-block h-16 px-12 rounded-full bg-playwize-purple hover:bg-purple-700 text-white font-black text-xl shadow-xl shadow-purple-100 transition-all hover:scale-105 active:scale-95 flex items-center gap-3 mx-auto w-fit"
            >
              Contact Support 🚀
            </a>
          </div>
        </div>
      </div>
    </main>
    </>
  )
}
